"""
Municipal Corporation Jalandhar Road Signs Project (McjRoadSigns)
Automated Suite: Cryptographic OTP and Security Token Validation Tests
"""

import hashlib
import secrets

def generate_mock_secure_otp() -> str:
    """Generates a secure 6-digit numeric token using secrets module."""
    return "".join(secrets.choice("0123456789") for _ in range(6))

def hash_mock_otp(otp: str) -> str:
    """Hashes the OTP token text using the SHA-256 algorithm."""
    return hashlib.sha256(otp.encode("utf-8")).hexdigest()

def test_secure_otp_geometry_properties():
    """Validates that tokens generated by secrets module are structurally sound."""
    token_1 = generate_mock_secure_otp()
    token_2 = generate_mock_secure_otp()
    
    assert len(token_1) == 6, "Security Failure: OTP must be exactly 6 digits long."
    assert token_1.isdigit(), "Security Failure: OTP must contain only numeric digits."
    assert token_1 != token_2, "Cryptographic Failure: Consecutive tokens must never match."

def test_sha256_one_way_hash_integrity():
    """Asserts that token text transforms into a valid, unpredictable 64-character hex hash string."""
    raw_token = "482015"
    hashed_output = hash_mock_otp(raw_token)
    
    assert len(hashed_output) == 64, "Hash Integrity Failure: SHA-256 output must be 64 characters long."
    assert hashed_output == hash_mock_otp(raw_token), "Hash Consistency Failure: Same input must yield identical signatures."
